/*
 * Content Protected VIA GPL-2.0-only
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
 * Copyright (c) 2023 Jackson Nicholas Brienen
 * https://github.com/JacksonBrienen/JWindowsFileDialog
 *
 * **PLEASE DO NOT REMOVE THIS HEADER**
 */
package com.github.jacksonbrienen.jwfd;

/**
 * JNIException is an exception thrown from the JNI functions called by <code>WindowsFileDialog</code>
 * @see WindowsFileDialog
 */
final class JNIException extends Exception{

    /**
     * Constructs a new <code>JNIException</code> with the specified detail message.
     * This message will be generated by a JNI function, and should include things like the file and line number where the exception is thrown.
     * @param msg the detail message. The detail message is saved for later retrieval by the {@link #getMessage()} method.
     */
    public JNIException(String msg) {
        super(msg);
    }

}